version: '3.4'

services:
  tendermint:
    container_name: tendermint
    build:
      context: .
    command: --proxy_app=persistent_kvstore
    ports: 
      - 26657:26657
      - 46656:46656
    volumes: 
      - ./storage:/home/tendermint/.tendermint
